// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleTaskWeb.Server;

namespace SampleTaskWeb.Server.Migrations
{
    [DbContext(typeof(DeviceDbContext))]
    partial class DeviceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("SampleTaskWeb.Shared.Device", b =>
                {
                    b.Property<Guid>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AdvancedEnvironmentConditions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceTypeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FailSafe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InsertInto19InchCabinet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallationPosition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TempMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempMin")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("TerminalElement")
                        .HasColumnType("INTEGER");

                    b.HasKey("InternalId");

                    b.ToTable("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
